site_name: EZ-FRCNN
site_url: https://docs.ezfrcnn.com

theme:
  name: material
  palette:
    scheme: slate  # This forces the dark theme
  features:
    - navigation.instant
    - navigation.top
    - navigation.sections
    - navigation.expand

nav:
  - Getting Started: index.md
  - ez-frcnn.annotation: annotation.md
  - ez-frcnn.characterize: characterize.md
  - ez-frcnn.image_augs: image_augs.md
  - ez-frcnn.inferencing: inferencing.md
  - ez-frcnn.plotting: plotting.md
  - ez-frcnn.training: training.md
  - ez-frcnn.utils: utils.md
  - Main Site: https://ezfrcnn.com

plugins:
  - search
  - mkdocstrings
